// Terms of Use for STEERER LLC — hand-authored rewrite of the Termly draft
// (substance preserved; added Subscriptions section, aligned the age policy
// with the Privacy Notice, replaced the $1 liability cap with a defensible
// formula, and added the California public-injunctive-relief carve-out).
// Styled via .legal__content in globals.css through data-custom-class hooks.
export const content = `<div data-custom-class="body">
  <div data-custom-class="title">TERMS OF USE</div>
  <div data-custom-class="subtitle"><strong>Last updated June 6, 2026</strong></div>

  <div data-custom-class="heading_1" id="agreement">AGREEMENT TO OUR LEGAL TERMS</div>
  <p data-custom-class="body_text">We are <strong>STEERER LLC</strong> ("<strong>Company</strong>," "<strong>we</strong>," "<strong>us</strong>," "<strong>our</strong>").</p>
  <p data-custom-class="body_text">We operate the mobile application Steerer (the "<strong>App</strong>") and the website <a data-custom-class="link" href="https://steerer.co">steerer.co</a> (the "<strong>Site</strong>"), as well as any other related products and services that refer or link to these legal terms (the "<strong>Legal Terms</strong>") (collectively, the "<strong>Services</strong>").</p>
  <p data-custom-class="body_text">You can contact us by email at <a data-custom-class="link" href="mailto:info@steerer.co">info@steerer.co</a>.</p>
  <p data-custom-class="body_text">These Legal Terms constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("<strong>you</strong>"), and STEERER LLC, concerning your access to and use of the Services. You agree that by accessing the Services, you have read, understood, and agreed to be bound by all of these Legal Terms. IF YOU DO NOT AGREE WITH ALL OF THESE LEGAL TERMS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SERVICES AND YOU MUST DISCONTINUE USE IMMEDIATELY.</p>
  <p data-custom-class="body_text">We will provide you with prior notice of any scheduled changes to the Services you are using. The modified Legal Terms will become effective upon posting or upon notifying you from <a data-custom-class="link" href="mailto:info@steerer.co">info@steerer.co</a>, as stated in the email message. By continuing to use the Services after the effective date of any changes, you agree to be bound by the modified terms.</p>
  <p data-custom-class="body_text">The Services are intended for users who are at least 13 years of age. Children under 13 are not permitted to register for or use the Services. All users who are minors in the jurisdiction in which they reside (generally under the age of 18) must have the permission of, and be directly supervised by, their parent or guardian to use the Services. If you are a minor, you must have your parent or guardian read and agree to these Legal Terms prior to you using the Services. Adults who add roster information about players under 18 must have the permission of each such player's parent or legal guardian, as further described in our <a data-custom-class="link" href="https://steerer.co/privacy">Privacy Notice</a>.</p>
  <p data-custom-class="body_text">We recommend that you print a copy of these Legal Terms for your records.</p>

  <div data-custom-class="heading_1">TABLE OF CONTENTS</div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#services">1. OUR SERVICES</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#ip">2. INTELLECTUAL PROPERTY RIGHTS</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#userreps">3. USER REPRESENTATIONS</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#userreg">4. USER REGISTRATION</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#subscriptions">5. SUBSCRIPTIONS AND PURCHASES</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#prohibited">6. PROHIBITED ACTIVITIES</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#ugc">7. USER GENERATED CONTRIBUTIONS</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#license">8. CONTRIBUTION LICENSE</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#mobile">9. MOBILE APPLICATION LICENSE</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#sitemanage">10. SERVICES MANAGEMENT</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#privacypolicy">11. PRIVACY POLICY</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#copyrightyes">12. COPYRIGHT INFRINGEMENTS</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#terms">13. TERM AND TERMINATION</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#modifications">14. MODIFICATIONS AND INTERRUPTIONS</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#law">15. GOVERNING LAW</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#disputes">16. DISPUTE RESOLUTION</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#corrections">17. CORRECTIONS</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#disclaimer">18. DISCLAIMER</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#liability">19. LIMITATIONS OF LIABILITY</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#indemnification">20. INDEMNIFICATION</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#userdata">21. USER DATA</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#electronic">22. ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#california">23. CALIFORNIA USERS AND RESIDENTS</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#misc">24. MISCELLANEOUS</a></div>
  <div data-custom-class="body_text"><a data-custom-class="link" href="#contact">25. CONTACT US</a></div>

  <div data-custom-class="heading_1" id="services">1. OUR SERVICES</div>
  <p data-custom-class="body_text">The information provided when using the Services is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, those persons who choose to access the Services from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.</p>
  <p data-custom-class="body_text">The Services are not tailored to comply with industry-specific regulations (Health Insurance Portability and Accountability Act (HIPAA), Federal Information Security Management Act (FISMA), etc.), so if your interactions would be subjected to such laws, you may not use the Services. You may not use the Services in a way that would violate the Gramm-Leach-Bliley Act (GLBA).</p>

  <div data-custom-class="heading_1" id="ip">2. INTELLECTUAL PROPERTY RIGHTS</div>
  <div data-custom-class="heading_2">Our intellectual property</div>
  <p data-custom-class="body_text">We are the owner or the licensee of all intellectual property rights in our Services, including all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics in the Services (collectively, the "Content"), as well as the trademarks, service marks, and logos contained therein (the "Marks").</p>
  <p data-custom-class="body_text">Our Content and Marks are protected by copyright and trademark laws (and various other intellectual property rights and unfair competition laws) and treaties in the United States and around the world.</p>
  <p data-custom-class="body_text">The Content and Marks are provided in or through the Services "AS IS" for your personal, non-commercial use or internal business purpose only.</p>
  <div data-custom-class="heading_2">Your use of our Services</div>
  <p data-custom-class="body_text">Subject to your compliance with these Legal Terms, including the "<a data-custom-class="link" href="#prohibited">PROHIBITED ACTIVITIES</a>" section below, we grant you a non-exclusive, non-transferable, revocable license to:</p>
  <ul>
    <li data-custom-class="body_text">access the Services; and</li>
    <li data-custom-class="body_text">download or print a copy of any portion of the Content to which you have properly gained access,</li>
  </ul>
  <p data-custom-class="body_text">solely for your personal, non-commercial use or internal business purpose.</p>
  <p data-custom-class="body_text">Except as set out in this section or elsewhere in our Legal Terms, no part of the Services and no Content or Marks may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission.</p>
  <p data-custom-class="body_text">If you wish to make any use of the Services, Content, or Marks other than as set out in this section or elsewhere in our Legal Terms, please address your request to: <a data-custom-class="link" href="mailto:info@steerer.co">info@steerer.co</a>. If we ever grant you the permission to post, reproduce, or publicly display any part of our Services or Content, you must identify us as the owners or licensors of the Services, Content, or Marks and ensure that any copyright or proprietary notice appears or is visible on posting, reproducing, or displaying our Content.</p>
  <p data-custom-class="body_text">We reserve all rights not expressly granted to you in and to the Services, Content, and Marks.</p>
  <p data-custom-class="body_text">Any breach of these Intellectual Property Rights will constitute a material breach of our Legal Terms and your right to use our Services will terminate immediately.</p>
  <div data-custom-class="heading_2">Your submissions and contributions</div>
  <p data-custom-class="body_text">Please review this section and the "<a data-custom-class="link" href="#prohibited">PROHIBITED ACTIVITIES</a>" section carefully prior to using our Services to understand the (a) rights you give us and (b) obligations you have when you post or upload any content through the Services.</p>
  <p data-custom-class="body_text"><strong>Submissions:</strong> By directly sending us any question, comment, suggestion, idea, feedback, or other information about the Services ("Submissions"), you agree to assign to us all intellectual property rights in such Submission. You agree that we shall own this Submission and be entitled to its unrestricted use and dissemination for any lawful purpose, commercial or otherwise, without acknowledgment or compensation to you.</p>
  <p data-custom-class="body_text"><strong>Contributions:</strong> The Services may invite you to chat, contribute to, or participate in team chats, match feeds, and other functionality during which you may create, submit, post, display, transmit, publish, distribute, or broadcast content and materials to us or through the Services, including but not limited to text, writings, video, audio, photographs, graphics, comments, or other material ("Contributions"). Any Submission that is publicly posted shall also be treated as a Contribution.</p>
  <p data-custom-class="body_text">You understand that Contributions may be viewable by other users of the Services, such as the members of your team or club.</p>
  <p data-custom-class="body_text"><strong>When you post Contributions, you grant us a license (including use of your name, trademarks, and logos):</strong> By posting any Contributions, you grant us an unrestricted, unlimited, irrevocable, perpetual, non-exclusive, transferable, royalty-free, fully-paid, worldwide right and license to: use, copy, reproduce, distribute, sell, resell, publish, broadcast, retitle, store, publicly perform, publicly display, reformat, translate, excerpt (in whole or in part), and exploit your Contributions (including, without limitation, your image, name, and voice) for any purpose, commercial, advertising, or otherwise, to prepare derivative works of, or incorporate into other works, your Contributions, and to sublicense the licenses granted in this section. Our use and distribution may occur in any media formats and through any media channels.</p>
  <p data-custom-class="body_text">This license includes our use of your name, company name, and franchise name, as applicable, and any of the trademarks, service marks, trade names, logos, and personal and commercial images you provide.</p>
  <p data-custom-class="body_text"><strong>You are responsible for what you post or upload:</strong> By sending us Submissions and/or posting Contributions through any part of the Services, you:</p>
  <ul>
    <li data-custom-class="body_text">confirm that you have read and agree with our "<a data-custom-class="link" href="#prohibited">PROHIBITED ACTIVITIES</a>" and will not post, send, publish, upload, or transmit through the Services any Submission nor post any Contribution that is illegal, harassing, hateful, harmful, defamatory, obscene, bullying, abusive, discriminatory, threatening to any person or group, sexually explicit, false, inaccurate, deceitful, or misleading;</li>
    <li data-custom-class="body_text">to the extent permissible by applicable law, waive any and all moral rights to any such Submission and/or Contribution;</li>
    <li data-custom-class="body_text">warrant that any such Submission and/or Contributions are original to you or that you have the necessary rights and licenses to submit such Submissions and/or Contributions and that you have full authority to grant us the above-mentioned rights in relation to your Submissions and/or Contributions; and</li>
    <li data-custom-class="body_text">warrant and represent that your Submissions and/or Contributions do not constitute confidential information.</li>
  </ul>
  <p data-custom-class="body_text">You are solely responsible for your Submissions and/or Contributions and you expressly agree to reimburse us for any and all losses that we may suffer because of your breach of (a) this section, (b) any third party's intellectual property rights, or (c) applicable law.</p>
  <p data-custom-class="body_text"><strong>We may remove or edit your Content:</strong> Although we have no obligation to monitor any Contributions, we shall have the right to remove or edit any Contributions at any time without notice if in our reasonable opinion we consider such Contributions harmful or in breach of these Legal Terms. If we remove or edit any such Contributions, we may also suspend or disable your account and report you to the authorities.</p>
  <div data-custom-class="heading_2">Copyright infringement</div>
  <p data-custom-class="body_text">We respect the intellectual property rights of others. If you believe that any material available on or through the Services infringes upon any copyright you own or control, please immediately refer to the "<a data-custom-class="link" href="#copyrightyes">COPYRIGHT INFRINGEMENTS</a>" section below.</p>

  <div data-custom-class="heading_1" id="userreps">3. USER REPRESENTATIONS</div>
  <p data-custom-class="body_text">By using the Services, you represent and warrant that: (1) all registration information you submit will be true, accurate, current, and complete; (2) you will maintain the accuracy of such information and promptly update such registration information as necessary; (3) you have the legal capacity and you agree to comply with these Legal Terms; (4) you are not under the age of 13, and you will not permit a child under 13 to register for or use the Services through your account; (5) you are not a minor in the jurisdiction in which you reside, or if a minor, you have received parental permission to use the Services; (6) if you add information about any person under the age of 18 to a team roster or otherwise to the Services, you have the permission of that person's parent or legal guardian to do so; (7) you will not access the Services through automated or non-human means, whether through a bot, script or otherwise; (8) you will not use the Services for any illegal or unauthorized purpose; and (9) your use of the Services will not violate any applicable law or regulation.</p>
  <p data-custom-class="body_text">If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Services (or any portion thereof).</p>

  <div data-custom-class="heading_1" id="userreg">4. USER REGISTRATION</div>
  <p data-custom-class="body_text">You may be required to register to use the Services. You agree to keep your password confidential and will be responsible for all use of your account and password. We reserve the right to remove, reclaim, or change a username you select if we determine, in our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable.</p>

  <div data-custom-class="heading_1" id="subscriptions">5. SUBSCRIPTIONS AND PURCHASES</div>
  <div data-custom-class="heading_2">Billing through app stores</div>
  <p data-custom-class="body_text">Certain features of the Services are offered through paid subscriptions. All subscriptions and other in-app purchases are processed exclusively through the Apple App Store or Google Play (each, an "App Store Provider") and are subject to the App Store Provider's own terms and payment policies in addition to these Legal Terms. We do not collect or store your full payment card details; payment is handled by the App Store Provider. The applicable price, billing period, and any free-trial terms are displayed in the App and in the App Store Provider's purchase flow before you confirm a purchase.</p>
  <div data-custom-class="heading_2">Automatic renewal</div>
  <p data-custom-class="body_text">Subscriptions automatically renew at the end of each subscription period, at the then-current price for your plan, unless you cancel through your App Store Provider account settings at least 24 hours before the end of the current period. Your App Store Provider charges the payment method associated with your store account within 24 hours prior to the start of each renewal period.</p>
  <div data-custom-class="heading_2">Cancellation</div>
  <p data-custom-class="body_text">You can cancel a subscription at any time in your Apple ID or Google Play account subscription settings. Cancellation takes effect at the end of the current billing period, and you will retain access to paid features until then. Deleting the App or your Steerer account does not by itself cancel a subscription — you must cancel through the App Store Provider.</p>
  <div data-custom-class="heading_2">Free trials</div>
  <p data-custom-class="body_text">If a subscription includes a free trial, the trial converts into a paid subscription at the end of the trial period — and your App Store Provider will charge you — unless you cancel before the trial ends. Trial terms (length and post-trial price) are disclosed in the purchase flow.</p>
  <div data-custom-class="heading_2">Refunds and price changes</div>
  <p data-custom-class="body_text">Refunds for purchases made through an App Store Provider are governed by that provider's refund policies and are requested directly from Apple or Google; we generally cannot issue refunds for store-billed purchases ourselves. We may change subscription prices from time to time; any price change will be communicated through the App Store Provider's mechanisms and will apply no earlier than your next billing period, and where required, will take effect only with your consent.</p>

  <div data-custom-class="heading_1" id="prohibited">6. PROHIBITED ACTIVITIES</div>
  <p data-custom-class="body_text">You may not access or use the Services for any purpose other than that for which we make the Services available. The Services may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.</p>
  <p data-custom-class="body_text">As a user of the Services, you agree not to:</p>
  <ul>
    <li data-custom-class="body_text">Systematically retrieve data or other content from the Services to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</li>
    <li data-custom-class="body_text">Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.</li>
    <li data-custom-class="body_text">Circumvent, disable, or otherwise interfere with security-related features of the Services, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Services and/or the Content contained therein.</li>
    <li data-custom-class="body_text">Disparage, tarnish, or otherwise harm, in our opinion, us and/or the Services.</li>
    <li data-custom-class="body_text">Use any information obtained from the Services in order to harass, abuse, or harm another person.</li>
    <li data-custom-class="body_text">Make improper use of our support services or submit false reports of abuse or misconduct.</li>
    <li data-custom-class="body_text">Use the Services in a manner inconsistent with any applicable laws or regulations.</li>
    <li data-custom-class="body_text">Engage in unauthorized framing of or linking to the Services.</li>
    <li data-custom-class="body_text">Upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with any party's uninterrupted use and enjoyment of the Services or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Services.</li>
    <li data-custom-class="body_text">Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.</li>
    <li data-custom-class="body_text">Delete the copyright or other proprietary rights notice from any Content.</li>
    <li data-custom-class="body_text">Attempt to impersonate another user or person or use the username of another user.</li>
    <li data-custom-class="body_text">Upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats ("gifs"), 1x1 pixels, web bugs, cookies, or other similar devices (sometimes referred to as "spyware" or "passive collection mechanisms" or "pcms").</li>
    <li data-custom-class="body_text">Interfere with, disrupt, or create an undue burden on the Services or the networks or services connected to the Services.</li>
    <li data-custom-class="body_text">Harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Services to you.</li>
    <li data-custom-class="body_text">Attempt to bypass any measures of the Services designed to prevent or restrict access to the Services, or any portion of the Services.</li>
    <li data-custom-class="body_text">Copy or adapt the Services' software, including but not limited to Flash, PHP, HTML, JavaScript, or other code.</li>
    <li data-custom-class="body_text">Except as permitted by applicable law, decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Services.</li>
    <li data-custom-class="body_text">Except as may be the result of standard search engine or Internet browser usage, use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Services, or use or launch any unauthorized script or other software.</li>
    <li data-custom-class="body_text">Use a buying agent or purchasing agent to make purchases on the Services.</li>
    <li data-custom-class="body_text">Make any unauthorized use of the Services, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses.</li>
    <li data-custom-class="body_text">Use the Services as part of any effort to compete with us or otherwise use the Services and/or the Content for any revenue-generating endeavor or commercial enterprise.</li>
  </ul>

  <div data-custom-class="heading_1" id="ugc">7. USER GENERATED CONTRIBUTIONS</div>
  <p data-custom-class="body_text">The Services may invite you to chat, contribute to, or participate in team chats and other functionality, and may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute, or broadcast content and materials to us or on the Services, including but not limited to text, writings, video, audio, photographs, graphics, comments, suggestions, or personal information or other material (collectively, "Contributions"). Contributions may be viewable by other users of the Services. As such, any Contributions you transmit may be treated as non-confidential and non-proprietary. When you create or make available any Contributions, you thereby represent and warrant that:</p>
  <ul>
    <li data-custom-class="body_text">The creation, distribution, transmission, public display, or performance, and the accessing, downloading, or copying of your Contributions do not and will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark, trade secret, or moral rights of any third party.</li>
    <li data-custom-class="body_text">You are the creator and owner of or have the necessary licenses, rights, consents, releases, and permissions to use and to authorize us, the Services, and other users of the Services to use your Contributions in any manner contemplated by the Services and these Legal Terms.</li>
    <li data-custom-class="body_text">You have the written consent, release, and/or permission of each and every identifiable individual person in your Contributions to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of your Contributions in any manner contemplated by the Services and these Legal Terms — and, where an identifiable individual is a minor, the consent of the minor's parent or legal guardian.</li>
    <li data-custom-class="body_text">Your Contributions are not false, inaccurate, or misleading.</li>
    <li data-custom-class="body_text">Your Contributions are not unsolicited or unauthorized advertising, promotional materials, pyramid schemes, chain letters, spam, mass mailings, or other forms of solicitation.</li>
    <li data-custom-class="body_text">Your Contributions are not obscene, lewd, lascivious, filthy, violent, harassing, libelous, slanderous, or otherwise objectionable (as determined by us).</li>
    <li data-custom-class="body_text">Your Contributions do not ridicule, mock, disparage, intimidate, or abuse anyone.</li>
    <li data-custom-class="body_text">Your Contributions are not used to harass or threaten (in the legal sense of those terms) any other person and to promote violence against a specific person or class of people.</li>
    <li data-custom-class="body_text">Your Contributions do not violate any applicable law, regulation, or rule.</li>
    <li data-custom-class="body_text">Your Contributions do not violate the privacy or publicity rights of any third party.</li>
    <li data-custom-class="body_text">Your Contributions do not violate any applicable law concerning child pornography, or otherwise intended to protect the health or well-being of minors.</li>
    <li data-custom-class="body_text">Your Contributions do not include any offensive comments that are connected to race, national origin, gender, sexual preference, or physical handicap.</li>
    <li data-custom-class="body_text">Your Contributions do not otherwise violate, or link to material that violates, any provision of these Legal Terms, or any applicable law or regulation.</li>
  </ul>
  <p data-custom-class="body_text">Any use of the Services in violation of the foregoing violates these Legal Terms and may result in, among other things, termination or suspension of your rights to use the Services.</p>

  <div data-custom-class="heading_1" id="license">8. CONTRIBUTION LICENSE</div>
  <p data-custom-class="body_text">By posting your Contributions to any part of the Services, you automatically grant us the license described in the "<a data-custom-class="link" href="#ip">INTELLECTUAL PROPERTY RIGHTS</a>" section above. We do not assert any ownership over your Contributions — you retain full ownership of all of your Contributions and any intellectual property rights or other proprietary rights associated with your Contributions. We are not liable for any statements or representations in your Contributions provided by you in any area on the Services. You are solely responsible for your Contributions to the Services and you expressly agree to exonerate us from any and all responsibility and to refrain from any legal action against us regarding your Contributions.</p>
  <p data-custom-class="body_text">We have the right, in our sole and absolute discretion, (1) to edit, redact, or otherwise change any Contributions; (2) to re-categorize any Contributions to place them in more appropriate locations on the Services; and (3) to pre-screen or delete any Contributions at any time and for any reason, without notice. We have no obligation to monitor your Contributions.</p>

  <div data-custom-class="heading_1" id="mobile">9. MOBILE APPLICATION LICENSE</div>
  <div data-custom-class="heading_2">Use license</div>
  <p data-custom-class="body_text">If you access the Services via the App, then we grant you a revocable, non-exclusive, non-transferable, limited right to install and use the App on wireless electronic devices owned or controlled by you, and to access and use the App on such devices strictly in accordance with the terms and conditions of this mobile application license contained in these Legal Terms. You shall not: (1) except as permitted by applicable law, decompile, reverse engineer, disassemble, attempt to derive the source code of, or decrypt the App; (2) make any modification, adaptation, improvement, enhancement, translation, or derivative work from the App; (3) violate any applicable laws, rules, or regulations in connection with your access or use of the App; (4) remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) posted by us or the licensors of the App; (5) use the App for any revenue-generating endeavor, commercial enterprise, or other purpose for which it is not designed or intended; (6) make the App available over a network or other environment permitting access or use by multiple devices or users at the same time; (7) use the App for creating a product, service, or software that is, directly or indirectly, competitive with or in any way a substitute for the App; (8) use the App to send automated queries to any website or to send any unsolicited commercial email; or (9) use any proprietary information or any of our interfaces or our other intellectual property in the design, development, manufacture, licensing, or distribution of any applications, accessories, or devices for use with the App.</p>
  <div data-custom-class="heading_2">Apple and Android devices</div>
  <p data-custom-class="body_text">The following terms apply when you use the App obtained from either the Apple App Store or Google Play (each an "App Distributor") to access the Services: (1) the license granted to you for our App is limited to a non-transferable license to use the application on a device that utilizes the Apple iOS or Android operating systems, as applicable, and in accordance with the usage rules set forth in the applicable App Distributor's terms of service; (2) we are responsible for providing any maintenance and support services with respect to the App as specified in the terms and conditions of this mobile application license contained in these Legal Terms or as otherwise required under applicable law, and you acknowledge that each App Distributor has no obligation whatsoever to furnish any maintenance and support services with respect to the App; (3) in the event of any failure of the App to conform to any applicable warranty, you may notify the applicable App Distributor, and the App Distributor, in accordance with its terms and policies, may refund the purchase price, if any, paid for the App, and to the maximum extent permitted by applicable law, the App Distributor will have no other warranty obligation whatsoever with respect to the App; (4) you represent and warrant that (i) you are not located in a country that is subject to a US government embargo, or that has been designated by the US government as a "terrorist supporting" country and (ii) you are not listed on any US government list of prohibited or restricted parties; (5) you must comply with applicable third-party terms of agreement when using the App, e.g., if you have a VoIP application, then you must not be in violation of their wireless data service agreement when using the App; and (6) you acknowledge and agree that the App Distributors are third-party beneficiaries of the terms and conditions in this mobile application license contained in these Legal Terms, and that each App Distributor will have the right (and will be deemed to have accepted the right) to enforce the terms and conditions in this mobile application license contained in these Legal Terms against you as a third-party beneficiary thereof.</p>

  <div data-custom-class="heading_1" id="sitemanage">10. SERVICES MANAGEMENT</div>
  <p data-custom-class="body_text">We reserve the right, but not the obligation, to: (1) monitor the Services for violations of these Legal Terms; (2) take appropriate legal action against anyone who, in our sole discretion, violates the law or these Legal Terms, including without limitation, reporting such user to law enforcement authorities; (3) in our sole discretion and without limitation, refuse, restrict access to, limit the availability of, or disable (to the extent technologically feasible) any of your Contributions or any portion thereof; (4) in our sole discretion and without limitation, notice, or liability, to remove from the Services or otherwise disable all files and content that are excessive in size or are in any way burdensome to our systems; and (5) otherwise manage the Services in a manner designed to protect our rights and property and to facilitate the proper functioning of the Services.</p>

  <div data-custom-class="heading_1" id="privacypolicy">11. PRIVACY POLICY</div>
  <p data-custom-class="body_text">We care about data privacy and security. Please review our Privacy Notice: <a data-custom-class="link" href="https://steerer.co/privacy">steerer.co/privacy</a>. By using the Services, you agree to be bound by our Privacy Notice, which is incorporated into these Legal Terms. Please be advised the Services are hosted in the United States. If you access the Services from any other region of the world with laws or other requirements governing personal data collection, use, or disclosure that differ from applicable laws in the United States, then through your continued use of the Services, you are transferring your data to the United States, and you expressly consent to have your data transferred to and processed in the United States.</p>
  <p data-custom-class="body_text">Children under 13 may not register for or use the Services. In accordance with the U.S. Children's Online Privacy Protection Act (COPPA), if we receive actual knowledge that we have collected personal information directly from a child under the age of 13 without the requisite and verifiable parental consent, we will delete that information from the Services as quickly as is reasonably practical. Roster information about players under 18 may be entered only by adults who have the permission of the player's parent or legal guardian, as described in our Privacy Notice.</p>

  <div data-custom-class="heading_1" id="copyrightyes">12. COPYRIGHT INFRINGEMENTS</div>
  <p data-custom-class="body_text">We respect the intellectual property rights of others. If you believe that any material available on or through the Services infringes upon any copyright you own or control, please immediately notify us using the contact information provided below (a "Notification"). A copy of your Notification will be sent to the person who posted or stored the material addressed in the Notification. Please be advised that pursuant to applicable law you may be held liable for damages if you make material misrepresentations in a Notification. Thus, if you are not sure that material located on or linked to by the Services infringes your copyright, you should consider first contacting an attorney.</p>

  <div data-custom-class="heading_1" id="terms">13. TERM AND TERMINATION</div>
  <p data-custom-class="body_text">These Legal Terms shall remain in full force and effect while you use the Services. WITHOUT LIMITING ANY OTHER PROVISION OF THESE LEGAL TERMS, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE SERVICES (INCLUDING BLOCKING CERTAIN IP ADDRESSES), TO ANY PERSON FOR ANY REASON OR FOR NO REASON, INCLUDING WITHOUT LIMITATION FOR BREACH OF ANY REPRESENTATION, WARRANTY, OR COVENANT CONTAINED IN THESE LEGAL TERMS OR OF ANY APPLICABLE LAW OR REGULATION. WE MAY TERMINATE YOUR USE OR PARTICIPATION IN THE SERVICES OR DELETE YOUR ACCOUNT AND ANY CONTENT OR INFORMATION THAT YOU POSTED AT ANY TIME, WITHOUT WARNING, IN OUR SOLE DISCRETION.</p>
  <p data-custom-class="body_text">If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or borrowed name, or the name of any third party, even if you may be acting on behalf of the third party. In addition to terminating or suspending your account, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress.</p>

  <div data-custom-class="heading_1" id="modifications">14. MODIFICATIONS AND INTERRUPTIONS</div>
  <p data-custom-class="body_text">We reserve the right to change, modify, or remove the contents of the Services at any time or for any reason at our sole discretion without notice. However, we have no obligation to update any information on our Services. We will not be liable to you or any third party for any modification, price change, suspension, or discontinuance of the Services.</p>
  <p data-custom-class="body_text">We cannot guarantee the Services will be available at all times. We may experience hardware, software, or other problems or need to perform maintenance related to the Services, resulting in interruptions, delays, or errors. We reserve the right to change, revise, update, suspend, discontinue, or otherwise modify the Services at any time or for any reason without notice to you. You agree that we have no liability whatsoever for any loss, damage, or inconvenience caused by your inability to access or use the Services during any downtime or discontinuance of the Services. Nothing in these Legal Terms will be construed to obligate us to maintain and support the Services or to supply any corrections, updates, or releases in connection therewith.</p>

  <div data-custom-class="heading_1" id="law">15. GOVERNING LAW</div>
  <p data-custom-class="body_text">These Legal Terms and your use of the Services are governed by and construed in accordance with the laws of the State of California applicable to agreements made and to be entirely performed within the State of California, without regard to its conflict of law principles.</p>

  <div data-custom-class="heading_1" id="disputes">16. DISPUTE RESOLUTION</div>
  <div data-custom-class="heading_2">Informal negotiations</div>
  <p data-custom-class="body_text">To expedite resolution and control the cost of any dispute, controversy, or claim related to these Legal Terms (each a "Dispute" and collectively, the "Disputes") brought by either you or us (individually, a "Party" and collectively, the "Parties"), the Parties agree to first attempt to negotiate any Dispute (except those Disputes expressly provided below) informally for at least thirty (30) days before initiating arbitration. Such informal negotiations commence upon written notice from one Party to the other Party.</p>
  <div data-custom-class="heading_2">Binding arbitration</div>
  <p data-custom-class="body_text">If the Parties are unable to resolve a Dispute through informal negotiations, the Dispute (except those Disputes expressly excluded below) will be finally and exclusively resolved by binding arbitration. YOU UNDERSTAND THAT WITHOUT THIS PROVISION, YOU WOULD HAVE THE RIGHT TO SUE IN COURT AND HAVE A JURY TRIAL. The arbitration shall be commenced and conducted under the Commercial Arbitration Rules of the American Arbitration Association ("AAA") and, where appropriate, the AAA's Supplementary Procedures for Consumer Related Disputes ("AAA Consumer Rules"), both of which are available at the <a data-custom-class="link" href="http://www.adr.org" target="_blank" rel="noopener noreferrer">American Arbitration Association (AAA) website</a>. Your arbitration fees and your share of arbitrator compensation shall be governed by the AAA Consumer Rules and, where appropriate, limited by the AAA Consumer Rules. The arbitration may be conducted in person, through the submission of documents, by phone, or online. The arbitrator will make a decision in writing, but need not provide a statement of reasons unless requested by either Party. The arbitrator must follow applicable law, and any award may be challenged if the arbitrator fails to do so. Except where otherwise required by the applicable AAA rules or applicable law, the arbitration will take place in California, United States. Except as otherwise provided herein, the Parties may litigate in court to compel arbitration, stay proceedings pending arbitration, or to confirm, modify, vacate, or enter judgment on the award entered by the arbitrator.</p>
  <p data-custom-class="body_text">If for any reason, a Dispute proceeds in court rather than arbitration, the Dispute shall be commenced or prosecuted in the state and federal courts located in California, and the Parties hereby consent to, and waive all defenses of lack of personal jurisdiction, and forum non conveniens with respect to venue and jurisdiction in such state and federal courts. Application of the United Nations Convention on Contracts for the International Sale of Goods and the Uniform Computer Information Transaction Act (UCITA) are excluded from these Legal Terms.</p>
  <p data-custom-class="body_text">In no event shall any Dispute brought by either Party related in any way to the Services be commenced more than one (1) year after the cause of action arose. If this provision is found to be illegal or unenforceable, then neither Party will elect to arbitrate any Dispute falling within that portion of this provision found to be illegal or unenforceable and such Dispute shall be decided by a court of competent jurisdiction within the courts listed for jurisdiction above, and the Parties agree to submit to the personal jurisdiction of that court.</p>
  <div data-custom-class="heading_2">Restrictions</div>
  <p data-custom-class="body_text">The Parties agree that any arbitration shall be limited to the Dispute between the Parties individually. To the full extent permitted by law, (a) no arbitration shall be joined with any other proceeding; (b) there is no right or authority for any Dispute to be arbitrated on a class-action basis or to utilize class action procedures; and (c) there is no right or authority for any Dispute to be brought in a purported representative capacity on behalf of the general public or any other persons. Notwithstanding the foregoing, nothing in these Legal Terms shall be construed as a waiver of your right to seek public injunctive relief in court to the extent such a waiver is prohibited by applicable law, including California law.</p>
  <div data-custom-class="heading_2">Exceptions to informal negotiations and arbitration</div>
  <p data-custom-class="body_text">The Parties agree that the following Disputes are not subject to the above provisions concerning informal negotiations and binding arbitration: (a) any Disputes seeking to enforce or protect, or concerning the validity of, any of the intellectual property rights of a Party; (b) any Dispute related to, or arising from, allegations of theft, piracy, invasion of privacy, or unauthorized use; (c) any claim for injunctive relief; and (d) any individual claim within the jurisdiction of a small claims court, which either Party may elect to bring in small claims court instead of arbitration. If this provision is found to be illegal or unenforceable, then neither Party will elect to arbitrate any Dispute falling within that portion of this provision found to be illegal or unenforceable and such Dispute shall be decided by a court of competent jurisdiction within the courts listed for jurisdiction above, and the Parties agree to submit to the personal jurisdiction of that court.</p>

  <div data-custom-class="heading_1" id="corrections">17. CORRECTIONS</div>
  <p data-custom-class="body_text">There may be information on the Services that contains typographical errors, inaccuracies, or omissions, including descriptions, pricing, availability, and various other information. We reserve the right to correct any errors, inaccuracies, or omissions and to change or update the information on the Services at any time, without prior notice.</p>

  <div data-custom-class="heading_1" id="disclaimer">18. DISCLAIMER</div>
  <p data-custom-class="body_text">THE SERVICES ARE PROVIDED ON AN AS-IS AND AS-AVAILABLE BASIS. YOU AGREE THAT YOUR USE OF THE SERVICES WILL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SERVICES AND YOUR USE THEREOF, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE MAKE NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE SERVICES' CONTENT OR THE CONTENT OF ANY WEBSITES OR MOBILE APPLICATIONS LINKED TO THE SERVICES AND WE WILL ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY (1) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT AND MATERIALS, (2) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SERVICES, (3) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (4) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICES, (5) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SERVICES BY ANY THIRD PARTY, AND/OR (6) ANY ERRORS OR OMISSIONS IN ANY CONTENT AND MATERIALS OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICES. WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SERVICES, ANY HYPERLINKED WEBSITE, OR ANY WEBSITE OR MOBILE APPLICATION FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND ANY THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</p>

  <div data-custom-class="heading_1" id="liability">19. LIMITATIONS OF LIABILITY</div>
  <p data-custom-class="body_text">IN NO EVENT WILL WE OR OUR DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT, LOST REVENUE, LOSS OF DATA, OR OTHER DAMAGES ARISING FROM YOUR USE OF THE SERVICES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE GREATER OF (A) THE AMOUNT PAID, IF ANY, BY YOU TO US DURING THE TWELVE (12) MONTH PERIOD PRIOR TO ANY CAUSE OF ACTION ARISING OR (B) ONE HUNDRED US DOLLARS ($100 USD). CERTAIN US STATE LAWS AND INTERNATIONAL LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.</p>

  <div data-custom-class="heading_1" id="indemnification">20. INDEMNIFICATION</div>
  <p data-custom-class="body_text">You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, and all of our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys' fees and expenses, made by any third party due to or arising out of: (1) your Contributions; (2) use of the Services; (3) breach of these Legal Terms; (4) any breach of your representations and warranties set forth in these Legal Terms; (5) your violation of the rights of a third party, including but not limited to intellectual property rights; or (6) any overt harmful act toward any other user of the Services with whom you connected via the Services. Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defense of such claims. We will use reasonable efforts to notify you of any such claim, action, or proceeding which is subject to this indemnification upon becoming aware of it.</p>

  <div data-custom-class="heading_1" id="userdata">21. USER DATA</div>
  <p data-custom-class="body_text">We will maintain certain data that you transmit to the Services for the purpose of managing the performance of the Services, as well as data relating to your use of the Services. Although we perform regular routine backups of data, you are solely responsible for all data that you transmit or that relates to any activity you have undertaken using the Services. You agree that we shall have no liability to you for any loss or corruption of any such data, and you hereby waive any right of action against us arising from any such loss or corruption of such data.</p>

  <div data-custom-class="heading_1" id="electronic">22. ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES</div>
  <p data-custom-class="body_text">Visiting the Services, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications, and you agree that all agreements, notices, disclosures, and other communications we provide to you electronically, via email and on the Services, satisfy any legal requirement that such communication be in writing. YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS, AND OTHER RECORDS, AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES, AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED BY US OR VIA THE SERVICES. You hereby waive any rights or requirements under any statutes, regulations, rules, ordinances, or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records, or to payments or the granting of credits by any means other than electronic means.</p>

  <div data-custom-class="heading_1" id="california">23. CALIFORNIA USERS AND RESIDENTS</div>
  <p data-custom-class="body_text">If any complaint with us is not satisfactorily resolved, you can contact the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs in writing at 1625 North Market Blvd., Suite N 112, Sacramento, California 95834 or by telephone at (800) 952-5210 or (916) 445-1254.</p>

  <div data-custom-class="heading_1" id="misc">24. MISCELLANEOUS</div>
  <p data-custom-class="body_text">These Legal Terms and any policies or operating rules posted by us on the Services or in respect to the Services constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce any right or provision of these Legal Terms shall not operate as a waiver of such right or provision. These Legal Terms operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time. We shall not be responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control. If any provision or part of a provision of these Legal Terms is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these Legal Terms and does not affect the validity and enforceability of any remaining provisions. There is no joint venture, partnership, employment or agency relationship created between you and us as a result of these Legal Terms or use of the Services. You agree that these Legal Terms will not be construed against us by virtue of having drafted them. You hereby waive any and all defenses you may have based on the electronic form of these Legal Terms and the lack of signing by the parties hereto to execute these Legal Terms.</p>

  <div data-custom-class="heading_1" id="contact">25. CONTACT US</div>
  <p data-custom-class="body_text">In order to resolve a complaint regarding the Services or to receive further information regarding use of the Services, please contact us at:</p>
  <p data-custom-class="body_text"><strong>STEERER LLC</strong><br />United States<br /><a data-custom-class="link" href="mailto:info@steerer.co">info@steerer.co</a></p>
</div>`;
